### ISSUE TITLE
용어 디비 오픈소스화

### ISSUE THREAD

**Issue by simnalamburt** [Devminjeong-eum/backend#48]
용어 수정이나 추가를 제안하는 과정이 좀 번거롭고 구글폼이어서 사람들 사이의 디스커션이 불가능한데 혹시 용어 디비 부분만이라도 오픈소스하실 생각이 있으신가요?

###### Reference
- https://x.com/jaypark_io/status/1803998400297189586?s=46&t=YRgjXbR9QAcflYZHuh-rbw

**Comment by RookieAND** [comment]
@simnalamburt
안녕하세요! 먼저 좋은 의견을 이슈에 남겨주셔서 정말 감사합니다.
다만 용어 데이터 DB 를 어떻게 오픈소스로 변환할지, 이와 관련한 정책을 어떻게 수립할지는 내부 논의가 필요해보입니다.
관련하여 의견이 정해지는데로 답변 드리겠습니다!

**Comment by simnalamburt** [comment]
걍 https://github.com/Fyrd/caniuse 처럼 용어 DB JSON을 github에 통째로 올리고, github에 PR 등으로 변경이 있을때마다 사이트에 반영시키는 github actions 를 세팅하면 되지않을까요

**Comment by RookieAND** [comment]
관련해서 어떻게 Action 을 설계하고 관련 정책을 수립할지 내부 논의 후에 결정해보겠습니다!
좋은 의견 주셔서 감사합니다 :)
